### ISSUE TITLE
Dispatcher re-architecture

### ISSUE THREAD

**Issue by davyodom** [kyma-incubator/knative-kafka#21]
In the current design, each subscription gets its own dispatcher deployment.  This allows for maximum isolation and independence of scale of each subscription.  However, it comes with a high resource cost, especially for installations with costly sidecars on each pod.  An option for redesign is to collapse dispatchers down to a single deployment per channel.  This potentially strikes a good balance between isolation of different event streams (high volume/low volume, sensitive/non-sensitive, etc), but increases resource efficiency when many subscriptions exist for the same channel.  These deployments would support horizontal scale with a replica count up to the number of partitions of the underlying kafka topic.

An understanding of resource cost of this consolidation should be gained to evaluate if additional changes are required on top. Each consumer of a consumer group with librdkafka carries a significant cost on its own (caching, polling, etc).  Measurements of memory and cpu usage will help decide how to manage number of consumers per consumer group in a single pod.

**Comment by travis-minke-sap** [comment]
As described above we will have one Dispatcher Deployment per KafkaChannel.  The number of replicas in the deployment will be minimally configurable (controller env vars is ok for now). Each Dispatcher pod will create a separate Kafka ConsumerGroup PER SUBSCRIPTION.  Each ConsumerGroup will contain a single Kafka Consumer.  The ConsumerGroups in each pod should align with each other so that the horizontal pod scaling is the way to control the consumer/partition scaling.  There won't be any intelligent load balancing or coordinating of partitions into pods, etc.

The plan is to remove the current subscription controller/reconciler by rolling the code back into the existing channel controller/reconciler.  This will eliminate some of the status complexity and align more closely with Knative standards as well. 

We will also be adding a new "controller" to the Dispatcher component based on the Knative eventing-contrib implementations (will have to try it out to be certain but it looks feasible).  This controller/reconciler will be watching our KafkaChannels and using the Subscription information added to the channel by the Knative SubscriptionController.  It will use that information to create the ConsumerGroups/Consumers mentioned above.  It will only operate on THE SPECIFIC KafkaChannel for which the Dispatcher Deployment/Pod is associated.

Reference Material
- https://github.com/knative/pkg/tree/master/injection
